spring:
  application:
    name: api

  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:construformas_db}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:construformas_db}
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:}

  sql:
    init:
      mode: always
      continue-on-error: false
